
language: go

go:
- "1.9.x"
- "1.10.x"
- "1.11.x"

env:
#- GO111MODULE=on

before_install:
#- go get github.com/stretchr/testify
#- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  make test;
